package com.qualizeal.javaapp06.operation;

public class FibonacciSeries {
	public String defineFibonacciSeries() {
		return "Fibonacci Sequence is a series of numbers in which each number, starting with 0 and 1, is generated by adding the two preceding numbers";
	}
	
	public String generateFibonacciSeries(int num) {
		int result = 0;
		int a = 0;
		int b = 1;
		String str = "";
		
		if(num < 0)
			return "-1";
		else if(num == 0)
			return "-2";
		else {
			while(a < num) {
				str += a + ", ";
				result = a + b;
				b = a;
				a = result;
			}
			return str.substring(0, str.length() - 2);
		}
	}
}
