
package com.qualizeal.javaapp06.operation;

public class FibonacciSeries {
	
	public String defineFibonacciSeries() {
		return "Fibonacci Sequence is a series of numbers starting with 0 and 1 in which each number is generated by adding the two preceding numbers.";
	}
	
	public String generateFibonacciSeries(int num){
		if(num < 0) return "-1";
		else if(num == 0) return "-2";
		else{
			String result = "0";
			int num1 = 0;
			int num2 = 1;
			int result1 = 0;
			
			while(result1 < num){
				result1 = num1 + num2;
				num1 = num2;
				num2 = result1;
				
				result += ", " + num1;
			}
			
			return result;
		}
	}
}
